name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v0.1.0

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build the package
      run: |
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
